### ISSUE TITLE
`move` and `swap` only affect values, not field state

### ISSUE THREAD

**Issue by dallonf** [final-form/final-form-arrays#10]
### Are you submitting a **bug report** or a **feature request**?

I believe this is a bug.

### What is the current behavior?

Here is a version of of the React Final Form Arrays example, modified to have validation errors that only appear when a field has been touched:

https://codesandbox.io/s/8k623wrrz9

1. Click "Add Customer"
2. Click in the "First Name" field, type something in (ex. "Homer")
3. Click in the "Last Name" field, but do not type in it
4. Click "Add Customer" again (Red text "Required" will appear under Customer 1's Last Name)
5. Click in Customer 2's "First Name" field, type something different (ex. "Marge")
6. Do not click in Customer 2's "Last Name" field.
7. Click the "Swap first two" button

The names have changed, but the "Required" error message is still in the same place (or, depending on your perspective, has moved to a different customer).

### What is the expected behavior?

I would expect the "touched" state to move along with the field, so that in this example the error would still be attached to Homer's last name, even though Homer has moved.

### What's your environment?

* final-form-arrays@1.0.4
* final-form@4.8.2
* react-final-form@3.6.2
* Chrome 67.0.3396.99
* macOS Sierra (10.12.6)

### Other information

The demo shows this happening with `swap`, but I originally observed the behavior with `move`.

**Comment by 311chaos** [comment]
I have a similar issue.

@dallonf - Did you come up with a work-around of any sorts?

There is also a similar discussion over on the react-final-form-arrays repo. 

https://github.com/final-form/react-final-form-arrays/issues/36

@erikras - I am not sure how to track this down through all the repos. I have followed it from react-final-form-arrays to final-form-arrays to `changeValue` in final-form. I am not sure if this is a bug, or if it is intended.

Is there any way to have the meta move with the input?

**Comment by erikras** [comment]
Great reporting, @dallonf.

**Comment by erikras** [comment]
I have confirmed this is a bug and have made some progress on it, but not yet conquered it. Stay tuned.

**Comment by 311chaos** [comment]
Thanks for the update @erikras. I really appreciate your time.

**Comment by erikras** [comment]
Published fix in [`v1.1.0`](https://github.com/final-form/final-form-arrays/releases/tag/v1.1.0).

Sandbox with updated dep:

[![Edit 🏁 React Final Form - Field Arrays](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ll94yk8437)

**Comment by erikras** [comment]
Published fix in [`v1.1.1`](https://github.com/final-form/final-form-arrays/releases/tag/v1.1.1).
