### ISSUE TITLE
feature request: a mutator which updates the value of arbitrary index of array

### ISSUE THREAD

**Issue by taneba** [final-form/final-form-arrays#12]
### Are you submitting a **bug report** or a **feature request**?
**feature request**

### What is the current behavior?
In order to update the value of arbitrary index of array, we have to remove the value of index and insert again.

### What is the expected behavior?
This feature enable to update the value at once (also without mutating the length of array).

**Comment by erikras** [comment]
Published fix in [`v1.1.0`](https://github.com/final-form/final-form-arrays/releases/tag/v1.1.0).
