### ISSUE TITLE
`move` and `swap` break form inputs

### ISSUE THREAD

**Issue by carlhueffmeier** [final-form/final-form-arrays#15]
### Are you submitting a **bug report** or a **feature request**?

I believe I found a bug.

### What is the current behavior?

These are the steps to reproduce:
1. Create two input fields
2. Swap them
3. Type into the *first* input field
4. The typed character will not appear in the first input field, but in the *second*

### What is the expected behavior?

Swapping or moving fields should preserve behavior.

### Sandbox Link

[![Edit 🏁 React Final Form - Field Arrays](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/3q04oy26r1)

To keep things as simple as possible, I reused the sandbox from the issue referenced below, simply upgrading the library version to 1.1.0.

### What's your environment?

The problem occurs with `final-form-arrays` version 1.1.0. Downgrading the package to 1.0.6 solves the problem.

### Other information

I believe the problem is caused by the latest change to the `move` and `swap` code in response to [this previous issue](https://github.com/final-form/final-form-arrays/issues/10).

[This commit](https://github.com/final-form/final-form-arrays/pull/14) looks especially suspicious.

I would be happy to work on it, if you give me some pointers on where to start 💪

**Comment by maciejmyslinski** [comment]
Yeah, I believe you've found a bug, indeed. I'll write a test case for it.

**Comment by tlenclos** [comment]
Hey guys, any news on this or some lead ? I can't implement a drag&drop sorting sadly due to this bug.

**Comment by tlenclos** [comment]
I had to move my form to https://github.com/jaredpalmer/formik, re-ordering is working but now we are facing performance issues.
`react-final-form` has just this bug preventing us from using it.

**Comment by maciejmyslinski** [comment]
I'm sorry to hear that @tlenclos 😢 
I was quite busy speaking publicly recently. I'm back on it.

**Comment by maciejmyslinski** [comment]
I wrote tests for `final-form-arrays` and it works correctly. Maybe the error is somewhere in `react-final-form-arrays` 🤔 
I'll try to investigate more next week.

**Comment by carlhueffmeier** [comment]
Thank you so much for looking into it Maciej! 🙏

After reading your message I had a glance at the code again and believe I have identified the issue 🙌
The problem seems to be that in addition to the field state, we are copying over all the event handler *functions* as well. (`change`, `blur`, `focus`)
I will explore the issue further and make a PR once I feel confident it's fixed.

I have to admit, I was a little bit reluctant to dive into the code because debugging the issue is so involved. I ended up building the package with`nps` and copying the `dist` directory into my test repos `node_modules` folder.
Certainly not the ideal integration testing workflow 😅 

Any hints on how to do facilitate development?

**Comment by maciejmyslinski** [comment]
@carlhueffmeier thanks! This library lacks integration tests with others from the ecosystem. I'll write such integration tests soon because it's [not the first time](https://github.com/final-form/final-form-arrays/issues/10) a similar issue happens.

**Comment by erikras** [comment]
Published fix in [`v1.1.1`](https://github.com/final-form/final-form-arrays/releases/tag/v1.1.1).
