### ISSUE TITLE
Move messes up pristine meta value

### ISSUE THREAD

**Issue by maciejmyslinski** [final-form/final-form-arrays#17]
### Are you submitting a **bug report** or a **feature request**?

bug report

### What is the current behavior?

We have an array of fruits.
Initial values are: `['', 'apple']`

#### Steps to reproduce:
* Clean `Fruit #2` field (enter empty value '')
* Click on move() button.

`Fruit #1` is *not* pristine

### What is the expected behavior?

`Fruit #1` field should be pristine since it equals `===` the initial value

### Sandbox Link

[![Edit 🐛 move messes up pristine meta value](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/l2lnnv1omm)

### What's your environment?

| package | version |
| --- | --- |
| final-form | 4.11 |
| react-final-form | 4.0.2 |
| final-form-arrays | 1.1.1 |
| react-final-form-arrays | 2.0.1 |

**Comment by erikras** [comment]
Gorgeous sandbox! Nice styling!

This is related to [how Final Form deletes values when the field is empty](https://github.com/final-form/final-form/blob/master/docs/faq.md#why-does--final-form-set-my--field-value-to-undefined).

If you provide a `parse={v => v}` prop to `Field`, it preserves the `''` value and it works as expected. See below:

[![Edit 🐛 move messes up pristine meta value](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/move-messes-up-pristine-meta-value-jvigo?fontsize=14)

I think this is not really a bug.
