### ISSUE TITLE
Shift does not preserve field's state.

### ISSUE THREAD

**Issue by maciejmyslinski** [final-form/final-form-arrays#18]
### Are you submitting a **bug report** or a **feature request**?

bug report

### What is the current behavior?

We have an array of fruits.
Initial values are: `['', '']`

#### Steps to reproduce:
1. Enter a value into `Fruit #1` field (eg. 'apple')
2. Blur the `Fruit #1` field. It becomes touched.
3. Click \`shift()\` button. 

The field that was never touched now has \`touched: true\`

### What is the expected behavior?

`Fruit #1` field should have `touched: false` since the definition of `touched` is:
> `true` if this field has ever gained and lost focus. `false` otherwise.

### Sandbox Link

[![Edit 🐛 shift() doesn't preserve field's state](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/l5rzyjo507)

### What's your environment?

| package | version |
| --- | --- |
| final-form | 4.11 |
| react-final-form | 4.0.2 |
| final-form-arrays | 1.1.1 |
| react-final-form-arrays | 2.0.1 |

**Comment by ventrz** [comment]
Also such thing is reproducible for **remove** action:

**Steps to reproduce:**
1. Focus `Fruit #1` field
2. Blur `Fruit #1` field (it becomes touched)
3. Remove `Fruit #1` field

`Fruit #2` field has `touched: true` state, but it has never been touched actually.

**Comment by erikras** [comment]
Fixed.  Requires `final-form@4.17.0` and `final-form-arrays@2.0.0`.

[![Edit 🐛 shift() doesn't preserve field's state](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/shift-doesnt-preserve-fields-state-j8s2k?fontsize=14)
