### ISSUE TITLE
fields.move causes an error when applied to two objects with different set of fields

### ISSUE THREAD

**Issue by dekhanov** [final-form/final-form-arrays#19]
### **Bug report** 
This issue was originally described at https://github.com/final-form/react-final-form-arrays/issues/39
It looks like it's more about the final-form-arrays, then about the react-final-form-arrays

### What is the current behavior?
`field.move` causes an error when applied to two objects with different set of fields.

Look at the demo: https://codesandbox.io/s/x94j811oj4
Open the console and click a `swap` button

### What is the expected behavior?
To swap objects with no error

### What's your environment?
See the CodeSandBox link

**Comment by seeden** [comment]
I see this error after merge 3.0.1 version

**Comment by erikras** [comment]
Published fix in [`v3.0.2`](https://github.com/final-form/final-form-arrays/releases/tag/v3.0.2).
