### ISSUE TITLE
Wrong fields state after pop and unshift

### ISSUE THREAD

**Issue by maciejmyslinski** [final-form/final-form-arrays#21]
### Are you submitting a **bug report** or a **feature request**?

bug report

### What is the current behavior?

We have an array of fruits.
Initial values are: `['', '']`

##### Steps to reproduce:

1. Modify field for Fruit #1 (eg. type 'orange')

2. Click on \`pop()\` button

3. Click on \`unshift('apple')\` button.

Fruit #1 is touched even though it was never focused
Fruit #2 is not touched even though it was focused and blurred.

### What is the expected behavior?

I would expect Fruit #1 to have touched: false since it was never focused.
I would expect Fruit #2 to have touched: true since it was focused and blurred.

### Sandbox Link

[![Edit 🐛 Wrong fields state after pop and unshift](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/jlvzoz4243)

### What's your environment?

| package | version |
| --- | --- |
| final-form | 4.11 |
| react-final-form | 4.0.2 |
| final-form-arrays | 1.1.0 |
| react-final-form-arrays | 2.0.1 |

**Comment by erikras** [comment]
Published fix in [`v3.0.0`](https://github.com/final-form/final-form-arrays/releases/tag/v3.0.0).

[![Edit 🐛 Wrong fields state after pop and unshift](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/wrong-fields-state-after-pop-and-unshift-6dvhm?fontsize=14)
