### ISSUE TITLE
Remove modifies other's inputs state

### ISSUE THREAD

**Issue by maciejmyslinski** [final-form/final-form-arrays#22]
### Are you submitting a **bug report** or a **feature request**?

bug report

### What is the current behavior?

We have an array of fruits.
Initial values are: `['', '']`

##### Steps to reproduce:

1. modify field for Fruit #2.

2. Click outside Fruit #2 field. It's state becomes `touched: true`

3. click `remove(0)`.

Field state `touched` is `false`

### What is the expected behavior?
Field state `touched` should remain `true`

### Sandbox Link

[![Edit 🐛 Remove modifies other input's state](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/y263o3rmrv)

### What's your environment?

| package | version |
| --- | --- |
| final-form | 4.11 |
| react-final-form | 4.0.2 |
| final-form-arrays | 1.1.1 |
| react-final-form-arrays | 2.0.1 |

**Comment by erikras** [comment]
Fixed in `final-form@4.17.0` and `final-form-arrays@2.0.0`.

[![Edit 🐛 Remove modifies other input's state](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/remove-modifies-other-inputs-state-ofr2d?fontsize=14)
