### ISSUE TITLE
Insert modifies other inputs state

### ISSUE THREAD

**Issue by maciejmyslinski** [final-form/final-form-arrays#24]
### Are you submitting a **bug report** or a **feature request**?

bug report

### What is the current behavior?

We have an array of fruits.
Initial values are: `['']`

##### Steps to reproduce:

1. Click insert(0, 'apple') button.

The input of index 1 (the last one) have `pristine: true` state even though it was never touched.

### What is the expected behavior?

The input of index 1 (the last one) should have `pristine: false` since it was never touched.

### Sandbox Link

[![Edit 🐛 Insert modifies other input's state](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/nrqxp0x6xl)

### What's your environment?

| package | version |
| --- | --- |
| final-form | 4.11 |
| react-final-form | 4.0.2 |
| final-form-arrays | 1.1.1 |
| react-final-form-arrays | 2.0.1 |

**Comment by erikras** [comment]
This is not a bug for the same reason as https://github.com/final-form/final-form-arrays/issues/23#issuecomment-511386091.

If you initialize the value to `{ fruits: [ undefined ] }`, it works as expected.
