### ISSUE TITLE
FieldArray is never pristine again

### ISSUE THREAD

**Issue by maciejmyslinski** [final-form/final-form-arrays#25]
### Are you submitting a **bug report** or a **feature request**?

bug report

### What is the current behavior?

When empty '' initial value is present, Array Fields are never pristine again like normal Fields.

Steps to reproduce:
1. Enter some value into the usual field, then revert the change. The field is pristine.
2. Enter some value into Fruit #1 field. Revert the change. The field is pristine.
3. Enter some value into Fruit #2 field. Revert the change. The field is NOT pristine.

### What is the expected behavior?

I would expect Fruit #2 field to be pristine.

### Sandbox Link

[![Edit 🐛 Field Array never pristine again](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/01v7kzvjkw)

### What's your environment?

| package | version |
| --- | --- |
| final-form | 4.11 |
| react-final-form | 4.0.2 |
| final-form-arrays | 1.1.1 |
| react-final-form-arrays | 2.0.1 |

**Comment by erikras** [comment]
This is stemming from similar `undefined`/`''` confusion as discussed here. https://github.com/final-form/final-form-arrays/issues/23#issuecomment-511386091 Not a bug.
