### ISSUE TITLE
Field subscribers and validators is not updated when using move

### ISSUE THREAD

**Issue by Juansasa** [final-form/final-form-arrays#28]
### Are you submitting a **bug report** or a **feature request**?
Bug report

### What is the current behavior?
When move field items field state is updated but not subscribers and validators this causes errors in many cases

### What is the expected behavior?
All states must be correctly moved

**Comment by erikras** [comment]
Published in [`v3.0.1`](https://github.com/final-form/final-form-arrays/releases/tag/v3.0.1).
