### ISSUE TITLE
Sort mutator

### ISSUE THREAD

**Issue by il421** [final-form/final-form-arrays#55]
Very often I need a sort mutator, for arrays, after any actions. For example, update a value, and sort after. I have added the method in my local project. And bind with arrayMutators. Works fine! May be I could contribute. I feel the method could be usefull

```js
const sort: Mutator<any> = (
  [name, compareFn]: [string, (a: any, b: any) => number],
  state: MutableState<any>,
  { setIn }: Tools<any>
) => {
  const sortedArray = state.formState.values[name].sort(compareFn)
  setIn(state, 'formState.values' + name, sortedArray)
}

export default sort;
```

**Comment by huan086** [comment]
This is not sufficient. The field state needs to be moved as well
