### ISSUE TITLE
Build 1.0.3 is missing typescript index.d.ts

### ISSUE THREAD

**Issue by rosskevin** [final-form/final-form-arrays#7]
### Are you submitting a **bug report** or a **feature request**?
bug

### What is the current behavior?
No ts bindings are in the build

### What is the expected behavior?
source `index.d.ts` is built and packaged as `"typings": "dist/index.d.js"`

### Sandbox Link
https://unpkg.com/final-form-arrays@1.0.3/dist/index.d.js

**Comment by erikras** [comment]
:shipit: ?
