### ISSUE TITLE
Release 3.0.3 version

### ISSUE THREAD

**Issue by nosovsh** [final-form/final-form-arrays#77]
The last released version (3.0.2) does not include this commit https://github.com/final-form/final-form-arrays/commit/916b7201b262ab6bb91099b7233e6d6d0463ff3f that fixes this bug https://github.com/final-form/final-form-arrays/pull/48 

Can you please latest master as the next minor version?

**Comment by indiesquidge** [comment]
@erikras thank you for all the work you've already done on this project and others like it, it's very much appreciated. I'm curious what it would take to get the 3.0.3 release out that includes bug fix #48. Is there anything you would like help with in moving that along?

**Comment by Vadim-Mostovenko** [comment]
@erikras hi, and thank you for all you have already done, our team using your library everywhere and it solves all the cases we have, but recently we faced the same problem described in #48 issue, can you give some feed back please about release 3.0.3?

**Comment by gertdreyer** [comment]
Version v3.1.0 has been released
